### ISSUE TITLE
Cannot do 'say' on a handle in binary mode

### ISSUE THREAD

**Issue by coke** [hoelzro/p6-io-string#10]
```
===> Testing: IO::String:ver('0.1.0'):auth('Rob Hoelz')
Cannot do 'say' on a handle in binary mode
  in block <unit> at t/04-bind.t line 9

Cannot do 'lines' on a handle in binary mode
  in block <unit> at t/05-lines.t line 11

# Looks like you planned 16 tests, but ran 1
# 12
===> Testing [FAIL]: IO::String:ver('0.1.0'):auth('Rob Hoelz')
Aborting due to test failure: IO::String:ver('0.1.0'):auth('Rob Hoelz') (use --force-test to override)
```

**Comment by coke** [comment]
@zoffixznet mentioned that this would be fixable with a version bump and that he would try to submit a PR to address the issue.

**Comment by zoffixznet** [comment]
PR to version-bump sent https://github.com/hoelzro/p6-io-string/pull/11

The bug itself got fixed a while back in https://github.com/hoelzro/p6-io-string/commit/13461282fe4b39831237721e315eacf62bdba1fa but because version never got bumped, zef still installs an older version, without that fix.

**Comment by zoffixznet** [comment]
Looking [more into it](https://irclog.perlgeek.de/perl6-dev/2017-06-02#i_14676453); I can't repro the problem and I suspect the reason coke had the problem was due to cache.

(the version still needs bumped tho IMO)
